/* Auto-generated by Crop Center Tool. */
const CROP_DESIGN_POINTS = {
  "after_proposal.JPG": [
    {
      "aspectRatio": 0.75,
      "x": 768,
      "y": 1024,
      "scale": 1536
    },
    {
      "aspectRatio": 1.332,
      "x": 768,
      "y": 897.342,
      "scale": 1536
    }
  ],
  "birds.jpeg": [
    {
      "aspectRatio": 0.66,
      "x": 368.14,
      "y": 385.625,
      "scale": 501.197
    },
    {
      "aspectRatio": 1.333,
      "x": 512,
      "y": 384,
      "scale": 1024
    }
  ],
  "engaged.jpeg": [
    {
      "aspectRatio": 0.589,
      "x": 1833.933,
      "y": 1536,
      "scale": 1809.408
    },
    {
      "aspectRatio": 1.328,
      "x": 2040,
      "y": 1536,
      "scale": 4080
    },
    {
      "aspectRatio": 1.992,
      "x": 2040,
      "y": 987.9298168604654,
      "scale": 3935.9123903720943
    }
  ],
  "engagement_ask.jpeg": [
    {
      "aspectRatio": 0.434,
      "x": 613.402,
      "y": 332.487,
      "scale": 287.647
    },
    {
      "aspectRatio": 1.777,
      "x": 591,
      "y": 332.5,
      "scale": 1182
    }
  ],
  "garden_gate.jpg": [
    {
      "aspectRatio": 0.667,
      "x": 1779,
      "y": 2668.5,
      "scale": 3558
    }
  ],
  "hands_on_face.jpeg": [
    {
      "aspectRatio": 0.667,
      "x": 1606.5,
      "y": 2409.5,
      "scale": 3213
    },
    {
      "aspectRatio": 1.594,
      "x": 1606.5,
      "y": 2941.804,
      "scale": 3206.419
    }
  ],
  "malini_rice.jpeg": [
    {
      "aspectRatio": 0.753,
      "x": 1536,
      "y": 2040,
      "scale": 3072
    },
    {
      "aspectRatio": 1.467,
      "x": 1528.459,
      "y": 2387.283,
      "scale": 3056.919
    },
    {
      "aspectRatio": 2.059,
      "x": 1522.208,
      "y": 2259.814,
      "scale": 3044.416
    }
  ],
  "on_bridge.jpg": [
    {
      "aspectRatio": 0.667,
      "x": 1331,
      "y": 1996.5,
      "scale": 2662
    },
    {
      "aspectRatio": 1.208,
      "x": 1329.478,
      "y": 1768.761,
      "scale": 2658.955
    },
    {
      "aspectRatio": 2.4,
      "x": 1329.659,
      "y": 1493.348,
      "scale": 2658.728
    }
  ],
  "redwood_grove_center.jpg": [
    {
      "aspectRatio": 0.667,
      "x": 1516.373,
      "y": 3376.206,
      "scale": 1546.098
    },
    {
      "aspectRatio": 1.225,
      "x": 1528.585,
      "y": 3124.241,
      "scale": 3054.309
    },
    {
      "aspectRatio": 2.082,
      "x": 1543.208,
      "y": 3553.065,
      "scale": 3086.416
    }
  ],
  "shyamala_rice.jpeg": [
    {
      "aspectRatio": 0.753,
      "x": 1536,
      "y": 2040,
      "scale": 3072
    },
    {
      "aspectRatio": 1.6,
      "x": 1526.434,
      "y": 2328.937,
      "scale": 3052.868
    },
    {
      "aspectRatio": 2.4,
      "x": 1526.434,
      "y": 2054.86,
      "scale": 3052.868
    }
  ],
  "tree_walk.jpg": [
    {
      "aspectRatio": 0.667,
      "x": 1824,
      "y": 2736,
      "scale": 3648
    },
    {
      "aspectRatio": 1.41,
      "x": 1822.692,
      "y": 3712.698,
      "scale": 3634.236
    },
    {
      "aspectRatio": 2.4,
      "x": 1826.522,
      "y": 3160.293,
      "scale": 3634.236
    }
  ],
  "with_family.jpeg": [
    {
      "aspectRatio": 1.159,
      "x": 1780.5,
      "y": 1536,
      "scale": 3561
    },
    {
      "aspectRatio": 2.4,
      "x": 1781.636,
      "y": 1283.133,
      "scale": 3558.727
    }
  ]
};

const RATIO_EPSILON = 0.0005;

function lerp(a, b, t) {
  return a + (b - a) * t;
}

function getCropCenterAndScale(imageName, aspectRatio) {
  const ratio = Number(aspectRatio);
  if (!imageName || !Number.isFinite(ratio)) {
    return null;
  }

  const points = CROP_DESIGN_POINTS[imageName];
  if (!Array.isArray(points) || points.length === 0) {
    return null;
  }

  const sorted = points.slice().sort((a, b) => a.aspectRatio - b.aspectRatio);
  const exact = sorted.find((point) => Math.abs(point.aspectRatio - ratio) <= RATIO_EPSILON);
  if (exact) {
    return { x: exact.x, y: exact.y, scale: exact.scale };
  }

  if (ratio <= sorted[0].aspectRatio) {
    return { x: sorted[0].x, y: sorted[0].y, scale: sorted[0].scale };
  }

  const last = sorted[sorted.length - 1];
  if (ratio >= last.aspectRatio) {
    return { x: last.x, y: last.y, scale: last.scale };
  }

  for (let i = 0; i < sorted.length - 1; i += 1) {
    const lower = sorted[i];
    const upper = sorted[i + 1];
    if (ratio >= lower.aspectRatio && ratio <= upper.aspectRatio) {
      const t = (ratio - lower.aspectRatio) / (upper.aspectRatio - lower.aspectRatio);
      return {
        x: lerp(lower.x, upper.x, t),
        y: lerp(lower.y, upper.y, t),
        scale: lerp(lower.scale, upper.scale, t)
      };
    }
  }

  return null;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { CROP_DESIGN_POINTS, getCropCenterAndScale };
}

if (typeof window !== "undefined") {
  window.CROP_DESIGN_POINTS = CROP_DESIGN_POINTS;
  window.getCropCenterAndScale = getCropCenterAndScale;
}
