/* Auto-generated by Crop Center Tool. */
const CROP_DESIGN_POINTS = {
  "after_proposal.JPG": [
    {
      "aspectRatio": 0.75,
      "x": 768,
      "y": 1024,
      "scale": 1536
    }
  ],
  "birds.jpeg": [
    {
      "aspectRatio": 1.3333333333333333,
      "x": 512,
      "y": 384,
      "scale": 1024
    }
  ],
  "engaged.jpeg": [
    {
      "aspectRatio": 1.778,
      "x": 2040,
      "y": 1536,
      "scale": 2856
    }
  ],
  "engagement_ask.jpeg": [
    {
      "aspectRatio": 1.778,
      "x": 591,
      "y": 332.5,
      "scale": 827.4
    }
  ],
  "garden_gate.jpg": [
    {
      "aspectRatio": 1.778,
      "x": 1781.799,
      "y": 2651.186,
      "scale": 3500.873
    }
  ],
  "hands_on_face.jpeg": [
    {
      "aspectRatio": 1.778,
      "x": 1606.5,
      "y": 2409.5,
      "scale": 2249.1
    }
  ],
  "malini_rice.jpeg": [
    {
      "aspectRatio": 1.778,
      "x": 1536,
      "y": 2040,
      "scale": 2150.4
    }
  ],
  "on_bridge.jpg": [
    {
      "aspectRatio": 0.4,
      "x": 1323.62,
      "y": 2008.749,
      "scale": 1587.401
    },
    {
      "aspectRatio": 0.636,
      "x": 1311.437,
      "y": 2230.729,
      "scale": 2059.263
    },
    {
      "aspectRatio": 1.778,
      "x": 1322.518,
      "y": 1618.918,
      "scale": 2632.787
    }
  ],
  "redwood_grove_center.jpg": [
    {
      "aspectRatio": 0.801,
      "x": 1490.372,
      "y": 3629.114,
      "scale": 1699.812
    },
    {
      "aspectRatio": 1.238,
      "x": 1517.04,
      "y": 3378.58,
      "scale": 2513.301
    },
    {
      "aspectRatio": 1.778,
      "x": 1547.676,
      "y": 3376.484,
      "scale": 3088.045
    }
  ],
  "shyamala_rice.jpeg": [
    {
      "aspectRatio": 1.778,
      "x": 1536,
      "y": 2040,
      "scale": 2150.4
    }
  ],
  "tree_walk.jpg": [
    {
      "aspectRatio": 1.778,
      "x": 1824,
      "y": 2736,
      "scale": 2553.6
    }
  ],
  "with_family.jpeg": [
    {
      "aspectRatio": 1.778,
      "x": 1780.5,
      "y": 1536,
      "scale": 2492.7
    }
  ]
};

const RATIO_EPSILON = 0.0005;

function lerp(a, b, t) {
  return a + (b - a) * t;
}

function getCropCenterAndScale(imageName, aspectRatio) {
  const ratio = Number(aspectRatio);
  if (!imageName || !Number.isFinite(ratio)) {
    return null;
  }

  const points = CROP_DESIGN_POINTS[imageName];
  if (!Array.isArray(points) || points.length === 0) {
    return null;
  }

  const sorted = points.slice().sort((a, b) => a.aspectRatio - b.aspectRatio);
  const exact = sorted.find((point) => Math.abs(point.aspectRatio - ratio) <= RATIO_EPSILON);
  if (exact) {
    return { x: exact.x, y: exact.y, scale: exact.scale };
  }

  if (ratio <= sorted[0].aspectRatio) {
    return { x: sorted[0].x, y: sorted[0].y, scale: sorted[0].scale };
  }

  const last = sorted[sorted.length - 1];
  if (ratio >= last.aspectRatio) {
    return { x: last.x, y: last.y, scale: last.scale };
  }

  for (let i = 0; i < sorted.length - 1; i += 1) {
    const lower = sorted[i];
    const upper = sorted[i + 1];
    if (ratio >= lower.aspectRatio && ratio <= upper.aspectRatio) {
      const t = (ratio - lower.aspectRatio) / (upper.aspectRatio - lower.aspectRatio);
      return {
        x: lerp(lower.x, upper.x, t),
        y: lerp(lower.y, upper.y, t),
        scale: lerp(lower.scale, upper.scale, t)
      };
    }
  }

  return null;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { CROP_DESIGN_POINTS, getCropCenterAndScale };
}

if (typeof window !== "undefined") {
  window.CROP_DESIGN_POINTS = CROP_DESIGN_POINTS;
  window.getCropCenterAndScale = getCropCenterAndScale;
}
