/* Auto-generated by Crop Center Tool. */
const CROP_DESIGN_POINTS = {
  "after_proposal.JPG": [
    {
      "aspectRatio": 0.75,
      "x": 768,
      "y": 1024,
      "scale": 1536
    },
    {
      "aspectRatio": 1.332,
      "x": 768,
      "y": 897.3419023136245,
      "scale": 1536
    }
  ],
  "birds.jpeg": [
    {
      "aspectRatio": 0.66,
      "x": 368.1397814910024,
      "y": 385.625321336761,
      "scale": 501.1970437017995
    },
    {
      "aspectRatio": 1.3333333333333333,
      "x": 512,
      "y": 384,
      "scale": 1024
    }
  ],
  "engaged.jpeg": [
    {
      "aspectRatio": 0.589,
      "x": 1833.9331619537277,
      "y": 1536,
      "scale": 1809.408
    },
    {
      "aspectRatio": 1.328125,
      "x": 2040,
      "y": 1536,
      "scale": 4080
    },
    {
      "aspectRatio": 1.992,
      "x": 2007.2354651162789,
      "y": 1030.0530915585587,
      "scale": 3992.393772583254
    }
  ],
  "engagement_ask.jpeg": [
    {
      "aspectRatio": 0.434,
      "x": 613.4023873952513,
      "y": 332.4871028282121,
      "scale": 287.64725192039106
    },
    {
      "aspectRatio": 1.7774436090225565,
      "x": 591,
      "y": 332.5,
      "scale": 1182
    }
  ],
  "garden_gate.jpg": [
    {
      "aspectRatio": 0.6666666666666666,
      "x": 1779,
      "y": 2668.5,
      "scale": 3558
    }
  ],
  "hands_on_face.jpeg": [
    {
      "aspectRatio": 0.6667358373106453,
      "x": 1606.5,
      "y": 2409.5,
      "scale": 3213
    },
    {
      "aspectRatio": 1.594,
      "x": 1606.5,
      "y": 2941.80438624679,
      "scale": 3206.4187821336764
    }
  ],
  "malini_rice.jpeg": [
    {
      "aspectRatio": 0.7529411764705882,
      "x": 1536,
      "y": 2040,
      "scale": 3072
    },
    {
      "aspectRatio": 1.467,
      "x": 1528.4594917331854,
      "y": 2387.2831685159435,
      "scale": 3056.9189834663707
    },
    {
      "aspectRatio": 2.059,
      "x": 1522.2079326923072,
      "y": 2259.8139750874125,
      "scale": 3044.4158653846143
    }
  ],
  "on_bridge.jpg": [
    {
      "aspectRatio": 0.6666666666666666,
      "x": 1331,
      "y": 1996.5,
      "scale": 2662
    },
    {
      "aspectRatio": 1.208,
      "x": 1329.477501502404,
      "y": 1768.761493389423,
      "scale": 2658.955003004808
    },
    {
      "aspectRatio": 2.4,
      "x": 1329.6592923677886,
      "y": 1493.3483323317305,
      "scale": 2658.7277644230767
    }
  ],
  "redwood_grove_center.jpg": [
    {
      "aspectRatio": 0.666595059076262,
      "x": 1511.259791803251,
      "y": 3782.425921246725,
      "scale": 1163.3071391499086
    },
    {
      "aspectRatio": 1.225,
      "x": 1551.5,
      "y": 3383.7755512811427,
      "scale": 3103
    },
    {
      "aspectRatio": 2.082,
      "x": 1551.5,
      "y": 3612.2196423368305,
      "scale": 3103
    }
  ],
  "shyamala_rice.jpeg": [
    {
      "aspectRatio": 0.7529411764705882,
      "x": 1536,
      "y": 2040,
      "scale": 3072
    },
    {
      "aspectRatio": 1.6,
      "x": 1526.4337849650356,
      "y": 2328.936844405596,
      "scale": 3052.867569930071
    },
    {
      "aspectRatio": 2.4,
      "x": 1526.4337849650356,
      "y": 2054.8601398601404,
      "scale": 3052.867569930071
    }
  ],
  "tree_walk.jpg": [
    {
      "aspectRatio": 0.6666666666666666,
      "x": 1824,
      "y": 2736,
      "scale": 3648
    },
    {
      "aspectRatio": 1.41,
      "x": 1822.6920891608368,
      "y": 3712.697989510485,
      "scale": 3634.2357954545405
    },
    {
      "aspectRatio": 2.4,
      "x": 1826.5223994755222,
      "y": 3160.2925043706277,
      "scale": 3634.2357954545405
    }
  ],
  "with_family.jpeg": [
    {
      "aspectRatio": 1.1591796875,
      "x": 1780.5,
      "y": 1536,
      "scale": 3561
    },
    {
      "aspectRatio": 2.4,
      "x": 1781.6363636363637,
      "y": 1283.1328671328667,
      "scale": 3558.7272727272725
    }
  ]
};

const RATIO_EPSILON = 0.0005;

function lerp(a, b, t) {
  return a + (b - a) * t;
}

function getCropCenterAndScale(imageName, aspectRatio) {
  const ratio = Number(aspectRatio);
  if (!imageName || !Number.isFinite(ratio)) {
    return null;
  }

  const points = CROP_DESIGN_POINTS[imageName];
  if (!Array.isArray(points) || points.length === 0) {
    return null;
  }

  const sorted = points.slice().sort((a, b) => a.aspectRatio - b.aspectRatio);
  const exact = sorted.find((point) => Math.abs(point.aspectRatio - ratio) <= RATIO_EPSILON);
  if (exact) {
    return { x: exact.x, y: exact.y, scale: exact.scale };
  }

  if (ratio <= sorted[0].aspectRatio) {
    return { x: sorted[0].x, y: sorted[0].y, scale: sorted[0].scale };
  }

  const last = sorted[sorted.length - 1];
  if (ratio >= last.aspectRatio) {
    return { x: last.x, y: last.y, scale: last.scale };
  }

  for (let i = 0; i < sorted.length - 1; i += 1) {
    const lower = sorted[i];
    const upper = sorted[i + 1];
    if (ratio >= lower.aspectRatio && ratio <= upper.aspectRatio) {
      const t = (ratio - lower.aspectRatio) / (upper.aspectRatio - lower.aspectRatio);
      return {
        x: lerp(lower.x, upper.x, t),
        y: lerp(lower.y, upper.y, t),
        scale: lerp(lower.scale, upper.scale, t)
      };
    }
  }

  return null;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { CROP_DESIGN_POINTS, getCropCenterAndScale };
}

if (typeof window !== "undefined") {
  window.CROP_DESIGN_POINTS = CROP_DESIGN_POINTS;
  window.getCropCenterAndScale = getCropCenterAndScale;
}
