/* Auto-generated by Crop Center Tool. */
const CROP_DESIGN_POINTS = {
  "flowerA.jpg": [
    {
      "aspectRatio": 1.305817849527871,
      "x": 2143.5,
      "y": 1641.5,
      "scale": 4287
    }
  ],
  "flowerB.jpg": [
    {
      "aspectRatio": 1.1231732776617953,
      "x": 2152,
      "y": 1916,
      "scale": 4304
    }
  ],
  "flowerC.jpg": [
    {
      "aspectRatio": 1.49800796812749,
      "x": 3008,
      "y": 2008,
      "scale": 6016
    }
  ]
};

const RATIO_EPSILON = 0.0005;

function lerp(a, b, t) {
  return a + (b - a) * t;
}

function getCropCenterAndScale(imageName, aspectRatio) {
  const ratio = Number(aspectRatio);
  if (!imageName || !Number.isFinite(ratio)) {
    return null;
  }

  const points = CROP_DESIGN_POINTS[imageName];
  if (!Array.isArray(points) || points.length === 0) {
    return null;
  }

  const sorted = points.slice().sort((a, b) => a.aspectRatio - b.aspectRatio);
  const exact = sorted.find((point) => Math.abs(point.aspectRatio - ratio) <= RATIO_EPSILON);
  if (exact) {
    return { x: exact.x, y: exact.y, scale: exact.scale };
  }

  if (ratio <= sorted[0].aspectRatio) {
    return { x: sorted[0].x, y: sorted[0].y, scale: sorted[0].scale };
  }

  const last = sorted[sorted.length - 1];
  if (ratio >= last.aspectRatio) {
    return { x: last.x, y: last.y, scale: last.scale };
  }

  for (let i = 0; i < sorted.length - 1; i += 1) {
    const lower = sorted[i];
    const upper = sorted[i + 1];
    if (ratio >= lower.aspectRatio && ratio <= upper.aspectRatio) {
      const t = (ratio - lower.aspectRatio) / (upper.aspectRatio - lower.aspectRatio);
      return {
        x: lerp(lower.x, upper.x, t),
        y: lerp(lower.y, upper.y, t),
        scale: lerp(lower.scale, upper.scale, t)
      };
    }
  }

  return null;
}

if (typeof module !== "undefined" && module.exports) {
  module.exports = { CROP_DESIGN_POINTS, getCropCenterAndScale };
}

if (typeof window !== "undefined") {
  window.CROP_DESIGN_POINTS = CROP_DESIGN_POINTS;
  window.getCropCenterAndScale = getCropCenterAndScale;
}
